model = "gpt-5.2-codex"
model_reasoning_effort = "xhigh"
sandbox_mode = "workspace-write"
network_access = true

notify = ["bash", "-lc", "afplay /System/Library/Sounds/Ping.aiff"]

[sandbox_workspace_write]
network_access = true

[features]
web_search_request = true
rmcp_client = true

[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp"]
command = "npx"

[mcp_servers.markitdown]
args = ["run", "--rm", "-i", "mcp/markitdown:latest"]
command = "docker"

[mcp_servers.chrome-devtools]
type = "stdio"
command = "npx"
args = ["chrome-devtools-mcp@latest"]
description = "Chrome DevTools MCP: run performance traces, inspect the DOM, and perform real-time debugging of your web pages â€” useful for browser automation, end-to-end testing, and capturing page artifacts."

[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp"
bearer_token_env_var = "GITHUB_MCP_API_TOKEN"

[projects."/Users/suzuneu/Projects/codex"]
trust_level = "trusted"

[projects."/Users/suzuneu/Projects/anond"]
trust_level = "trusted"

[projects."/Users/suzuneu/Projects/sharey"]
trust_level = "trusted"

[projects."/Users/suzuneu/Projects/kyujin"]
trust_level = "trusted"

[projects."/Users/suzuneu/Projects/synchrony-rs"]
trust_level = "trusted"

[projects."/Users/suzuneu/Projects/miq-gen-rs"]
trust_level = "trusted"

[projects."/Users/suzuneu/Projects/chatgpt-discord"]
trust_level = "trusted"

[projects."/Users/suzuneu/Projects/chatgpt-web-rs"]
trust_level = "trusted"

[projects."/Users/suzuneu"]
trust_level = "untrusted"

[projects."/Users/suzuneu/Projects/bjrs"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.2" = "gpt-5.2-codex"
